export const UI_TEXT = {
  appSection: "Administración",
  panelTitle: "Panel de Control",
  totalContacts: "Total de Contactos",
  pending: "Pendientes",
  attended: "Atendidos",
  name: "Nombre",
  email: "Correo electrónico",
  phone: "Teléfono",
  message: "Mensaje",
  status: "Estado",
  actions: "Acciones",
  markAsAttended: "Marcar como atendido",
  delete: "Eliminar",
  logout: "Cerrar sesión",
  contacted: "Atendido",
  notContacted: "Pendiente",
}